cc = clang++ -std=c++20

assignment: assignment.cpp
	${cc} assignment.cpp -o out/assignment

constants: constants.cpp 
	${cc} constants.cpp -o out/constants

enums: enums.cpp
	${cc} enums.cpp -o out/enums

pointers: pointers.cpp
	${cc} pointers.cpp -o out/pointers

namespaces: namespaces.cpp
	${cc} namespaces.cpp -o out/namespaces

exceptions: exceptions.cpp
	${cc} exceptions.cpp -o out/exceptions

arrays: arrays.cpp
	${cc} arrays.cpp -o out/arrays

clean:
	rm out/*
