cc = clang++ -std=c++20

assignment:
	${cc} assignment.cpp -o out/assignment

constants:
	${cc} constants.cpp -o out/constants

enums:
	${cc} enums.cpp -o out/enums

pointers:
	${cc} pointers.cpp -o out/pointers

namespaces:
	${cc} namespaces.cpp -o out/namespaces

exceptions:
	${cc} exceptions.cpp -o out/exceptions

clean:
	rm out/*
