cc = clang++ -std=c++20

bad_container: bad_container.cpp
	${cc} bad_container.cpp -o out/bad_container

bad_parameterized: bad_parameterized.cpp
	${cc} bad_parameterized.cpp -o out/bad_parameterized

bad_pair: bad_pair.cpp
	${cc} bad_pair.cpp -o out/bad_pair

clean:
	rm out/*
